# Generated by Django 2.2.6 on 2019-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gray',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='photo',
            field=models.ImageField(default='SOME STRING', upload_to='photos/'),
        ),
    ]
