# Generated by Django 2.2.6 on 2019-12-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20191202_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='photo',
            new_name='image',
        ),
    ]
